### ISSUE TITLE
Bugs From "preprocess_movie_imdb.py" file

### ISSUE THREAD

**Issue by Howene** [jennyzhang0215/MovieLens-IMDB#1]
Hi, thanks for your codes. When I run your codes of the  "preprocess_movie_imdb.py" file, it reported that the line 638 "assert len(imdb_id) == 9" was an error. 

Then I commented this line and tried to continue run the codes, it reported another bugs as follows:
"
# found1652/1681, dropped: 8 (not matched) + 3 (>2 titles)
# mapped (director): 12621, # mapped (writer): 12518
Traceback (most recent call last):
  File "preprocess_movie_imdb.py", line 682, in <module>
    year_diff_thres=4, chosen_title_type_l=["movie", "tvmovie", "tvminiseries", "video"], COS_SIM_THRES=0.3)
  File "preprocess_movie_imdb.py", line 664, in match
    ["writer_id", "name"])
  File "preprocess_movie_imdb.py", line 496, in _gen_unique_info
    unique_l = [[id, people_id2name_dic[id]] for id in unique_.values]
  File "preprocess_movie_imdb.py", line 496, in <listcomp>
    unique_l = [[id, people_id2name_dic[id]] for id in unique_.values]
KeyError: 'nm0799875'
"

Could you help me solve this problem? Or if you have the processed data about Moivelens 10m/20m, could you send them to me? My email is springmore123@gmail.com.

**Comment by Howene** [comment]
Hi, could you help me? These datasets are important for me. Thanks!
